// Code generated by Gottani; see https://github.com/ktateish/gottani/. DO NOT EDIT.
package main

import (
	"fmt"
	"math"
)

// F() returns the value of Pi
//
//line example.com/lib/lib.go:5
func F() float64 {
	return math.Pi
}

//line main.go:9
func main() {
	fmt.Println(F())
}
