// Code generated by Gottani; see https://github.com/ktateish/gottani/. DO NOT EDIT.
package main

import (
	"bytes"
	"fmt"
)

//line example.com/lib/lib.go:5
func NewT() *T {
	return &T{new(bytes.Buffer)}
}

func (t *T) Write(b []byte) (int, error) {
	return t.buf.Write(b)
}

func (t *T) String() string {
	return t.buf.String()
}

//line example.com/lib/types.go:7
type T struct {
	buf *bytes.Buffer
}

//line main.go:9
func main() {
	w := NewT()
	fmt.Fprintf(w, "Hello world!")
	fmt.Println(w.String())
}
