// Code generated by Gottani; see https://github.com/ktateish/gottani/. DO NOT EDIT.
package main

import "fmt"

// DEAFULT is the default T
//
//line example.com/lib/lib.go:3
var DEFAULT *T

//line example.com/lib/lib.go:11
func init() {
	// initial value of the DEFAULT is 128
	DEFAULT = NewT(128)
}

// NewT returns a pointer to the type T
func NewT(v int) *T {
	return &T{v}
}

// type T
type T struct {
	v int
}

// Value returns the value of t
func (t *T) Value() int {
	return t.v
}

// Value sets the value of t to the given v
func (t *T) SetValue(v int) {
	t.v = v
}

//line main.go:9
func main() {
	// create new lib.T
	t := NewT(10)
	fmt.Println(t.Value())
	t.SetValue(t.Value() * 2)
	fmt.Println(t.Value())

	// use lib.DEFAULT through local pointer
	p := DEFAULT
	fmt.Println(p.Value())
	p.SetValue(p.Value() * 2)
	fmt.Println(p.Value())

	// use lib.DEFAULT directly
	fmt.Println(DEFAULT.Value())
	DEFAULT.SetValue(DEFAULT.Value() * 2)
	fmt.Println(DEFAULT.Value())
}
