// Code generated by Gottani; see https://github.com/ktateish/gottani/. DO NOT EDIT.
package main

//line example.com/lib/lib.go:3
type lib_foo int

type Foos []lib_foo

func (f Foos) String() string { return "x" }

//line main.go:5
type foo int

func main() {
	_ = foo(0)
	_ = Foos{}
}
