// Code generated by Gottani; see https://github.com/ktateish/gottani/. DO NOT EDIT.
package main

import (
	"fmt"
	"math"
)

//line example.com/libx/libx.go:5
// F() returns the value of Pi
func F() float64 {
	return math.Pi
}

//line example.com/liby/liby.go:5
// F() returns the value of Pi
func liby_F() float64 {
	return math.Pi
}

//line main.go:10
func main() {
	fmt.Println(F())
	fmt.Println(liby_F())
}
