// Code generated by Gottani; see https://github.com/ktateish/gottani/. DO NOT EDIT.
package main

import "fmt"

//line example.com/lib/lib.go:5
type Type[T any] struct{}

func New[T any](v T) Type[T] {
	return Type[T]{}
}

func (t Type[T]) Foo() {
	fmt.Printf("Hello from %T\n", t)
}

//line main.go:5
func main() {
	foo := New(10)

	foo.Foo()
}
