name: Go test

on: push

jobs:
  go-test:
    name: go test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.1'
      - run: go build ./...
      - run: go test ./...
